services:
  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d stats"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ewm-network
    volumes:
      - stats-db-data:/var/lib/postgresql/data

  ewm-stats-service:
    build: ewm-stats-service
    container_name: ewm-stats-service
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - STATS_SERVICE_URL=http://ewm-stats-service:9090
    networks:
      - ewm-network

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ewm"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ewm-network
    volumes:
      - ewm-db-data:/var/lib/postgresql/data

  ewm-main-service:
    build: ewm-main-service
    container_name: ewm-main-service
    ports:
      - "8080:8080"
    depends_on:
      ewm-db:
        condition: service_healthy
      ewm-stats-service:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - STATS_SERVICE_URL=http://ewm-stats-service:9090
    networks:
      - ewm-network

networks:
  ewm-network:
    driver: bridge

volumes:
  stats-db-data:
  ewm-db-data:
