server:
  port: 8080
  shutdown: graceful
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: ewm-main-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://ewm-db:5432/ewm
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: false
        jdbc:
          batch_size: 20
    show-sql: false
    open-in-view: false
  sql:
    init:
      mode: always
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false

stats-service:
  url: ${STATS_SERVICE_URL:http://ewm-stats-service:9090}

logging:
  level:
    ru.practicum: INFO
    org.springframework: WARN
    org.hibernate: WARN