server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: ewm-main-service
  datasource:
    url: jdbc:postgresql://ewm-db:5432/ewm
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: false
        jdbc:
          batch_size: 20
    show-sql: false
    open-in-view: false
  sql:
    init:
      mode: always

stats-service:
  url: http://ewm-stats-service:9090

logging:
  level:
    ru.practicum: INFO
    org.springframework: WARN
    org.hibernate: WARN
